apiVersion: v1
kind: ConfigMap
metadata:
  name: workhub-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "workhub"
  DB_USER: "workhub"
  SHOW_SQL: "false"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"